# Funding links shown on the repository sidebar
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: []
ko_fi: ""
buy_me_a_coffee: ""
custom:
  - "https://apps.microsoft.com/store/detail/openmonitor"
